### ISSUE TITLE
Testing session

### ISSUE THREAD

**Issue by ReneeSeet** [CS2103AUG2017-W15-B1/Main#74]
Hi!
Here are some of the issues that I found while using Rubrika: 
1. Result Display does not at times update. 
2. when I opened help as first command, subsequent command does not work 
3. theme does not work yet 

good points: 
1. autocomplete is working 
2. sort is working

**Comment by john19950730** [comment]
Hi, thanks for testing out our application, I would like to respond to your remarks as follows:

Firstly, can you provide more details as to the commands you have entered that leads to the Result Display not updating? Screenshot(s) would be nice.

Second, did you remember to close the help window, before trying to type subsequent commands? Any screenshots to help reproducing the problem would be really helpful for us!

Thirdly, `theme` command takes in arguments that are case-sensitive, please ensure your input is correct in order to ensure the desired results are displayed.

Thanks for your review, and really appreciate your input on the problems you encounter when using our application. Also, thanks for raising the good points you feel that is nice about our application.
